### ISSUE TITLE
Install ICAP Client on docker image with jmeter

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/k8-traffic-generator#111]
Location - https://github.com/filetrust/k8-traffic-generator/tree/master/upwork-devs/faisal-adnan/JMeter

**Comment by MaNe2020** [comment]
@dpatel7 @faisaladnanpeltops we can close this one.
It is already done. Both this
https://github.com/k8-proxy/k8-performance-use-cases/tree/master/upword-devs/marija-neskovic/docker-jmeter-c-icap 
and this https://github.com/k8-proxy/p-k8-jmeter-test-engine-v1/tree/master/upwork-devs/MaNe2020/docker-icap-jmeter-testdata
are images for this.
