### ISSUE TITLE
Issue consuming read me  due to lack of configuration 

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/k8-traffic-generator#116]
@ggrig we need these issue to looked at please

1. When we run our JMX script using steps in read me and when we get the results from minio is blank html. there is no information.
2. How to write results to specific directories

3. Need to understand how we are handling secrets

4. How can we get single report for full run instead of by per pods

5. Anything specific needs to be included in our JMX script, this needs to be specified in the readme

**Comment by ggrig** [comment]
Would you please clarify if this is about run.ps1 script in C:\Glasswall\ggrig\k8-traffic-generator\upwork-devs\faisal-adnan\JMeter?

**Comment by dpatel7** [comment]
@ggrig Is general about how to do full setup and running any jmx script using the traffic generator. as mention when we running any other jmx script we are not able to get result in Minio, the result is blank

**Comment by ggrig** [comment]
@dpatel7 
Can we make it more specific? 
Which particular script in the repository do you run that does not produce the expected result?

**Comment by dpatel7** [comment]
@ggrig We tied to run ps1 script in repo and pass our jmx script to it and when we navigate to minio couldn't see results

**Comment by ggrig** [comment]
@dpatel7 
OK, I will start investigating this with https://github.com/k8-proxy/k8-traffic-generator/tree/master/upwork-devs/faisal-adnan/JMeter (the only test that contains a JMX script). Then we'll see what we can do with the other test cases

**Comment by dpatel7** [comment]
@ggrig here is link to the script we are trying to use. https://github.com/filetrust/ICAP_Jmeter_Performance_Image/blob/master/Docker/ICAP.jmx

**Comment by ggrig** [comment]
@dpatel7 
Thank you!
Have you been trying to utilize it with the JMeter test?

**Comment by ggrig** [comment]
This will be resolved as a part of https://github.com/k8-proxy/p-k8-jmeter-test-engine-v1 project
