### ISSUE TITLE
Integrate with elastic, minio and execute tests for multiple users

### ISSUE THREAD

**Issue by pranaysahith** [k8-proxy/k8-traffic-generator#40]
* Add elastic pods for logging
* Create video of this executing for a couple minutes
* Change the target website to be minio

**Comment by markband** [comment]
Hi @pranaysahith please provide an update on this task. It has been in progress for some time. Thanks!

**Comment by pranaysahith** [comment]
Hi @markband  I have started working on #48 I will come back to this once #48 is completed.
