### ISSUE TITLE
Use the Rebuild engine as the target system

### ISSUE THREAD

**Issue by faisaladnanpeltops** [k8-proxy/k8-traffic-generator#58]
See Rebuild API here:
https://engineering.glasswallsolutions.com/docs/products/cloud-sdk/rebuild/rebuild-api

Get a free token here:
https://glasswall-store.com/products/glasswall-rebuild-cloud-in-shared-cloud-environment?variant=33739907006604

**Comment by ggrig** [comment]
We'll be using min.io as file input and output queues. 
Helpful link https://gist.github.com/balamurugana/c59e868a36bb8a549fe863d22d6f0678

**Comment by ggrig** [comment]
Sending Minio Logs to Kibana:
https://github.com/minio/minio/issues/7254

**Comment by ggrig** [comment]
Single Job starts controller Pod (which then creates other Pods)
https://kubernetes.io/docs/concepts/workloads/controllers/job/
https://github.com/kubernetes/examples/blob/master/staging/spark/README.md

**Comment by yardenshoham** [comment]
I did something that might help you. https://github.com/filetrust/k8-traffic-generator/tree/8821b7c446ebddf35c45f2f807978206aefac826/upwork-devs/yarden-shoham/file-drop.co.uk.

**Comment by ggrig** [comment]
Thanks, Yarden.
I have watched your presentation during the AMA meeting and I certainly will be using it
