### ISSUE TITLE
Send JMeter test report to ELK in JSON Format.

### ISSUE THREAD

**Issue by faisaladnanpeltops** [k8-proxy/k8-traffic-generator#62]
See description in #61

**Comment by RhiaRodriguez** [comment]
Hello @faisaladnanpeltops Please see this jmx file. It generates a json file report. 
[GlasswallPOC.jmx.zip](https://github.com/filetrust/k8-traffic-generator/files/5181817/GlasswallPOC.jmx.zip)

**Comment by MaNe2020** [comment]
@faisaladnanpeltops you can assign this one to me also.
It is part of: https://github.com/k8-proxy/p-k8-jmeter-test-engine-v1/issues/3
So I can investigate it.
